source 'https://github.com/CocoaPods/Specs.git'
target 'ABPluginExample iOS' do
#TAG-GIDEROS-POD-IOS
  use_frameworks!

  pod 'TapjoySDK'
  pod 'Firebase/Core'
  pod 'Firebase/AdMob'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Firebase/RemoteConfig'
end
target 'ABPluginExample AppleTV' do
#TAG-GIDEROS-POD-ATV
end

